--- 
- hosts: localhost
  become: true
  tasks:

  - name: 'Install NGINX'
    apt:
      name: nginx
      state: latest
      update_cache: true
    register: install_nginx_info
    ignore_errors: true

  - name: printing out nginx install info
    debug:
      msg: "{{ install_nginx_info }}"
    
  - name: 'Start NGINX Service'
    service:
      name: nginx
      state: started

 # - name: 'Reloaded NGINX Service'
  #  service:
  #    name: nginx
  #    state: reloaded
    
  
